-- جابز ٹیبل
create table jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text,
  location text default 'Layyah',
  salary text,
  description text,
  contact text not null,
  job_type text,
  deletion_key text not null,
  created_at timestamp default now()
);

-- RLS پالیسی (anon کو سب کاموں کی اجازت)
alter table jobs enable row level security;
create policy "anon_all" on jobs for all to anon using (true) with check (true);
